### ISSUE TITLE
Travail en équipe

### ISSUE THREAD

**Issue by slobberbone** [nouknouk/domonode#1]
Salut, désolé, je ne savais pas comment te contacter autrement.
Connais-tu NextDom ?
Nous avons forké jeedom il y a 2 ans et qq maintenant et nous avons modifié + de 80% du code.
Ne voudrais-tu pas que l'on joigne nos éfforts ? Je suis quasimeent certain que nouq avons des besoins et philosophies qui se rejoignent !

voici notre site : https://www.nextdom.org
et notre discord si tu veux discuter un peu et voir ce que nous pourrions faire ensemble : https://discord.gg/DdDtWw

@ bientôt j'espère !

Slobberbone

**Comment by nouknouk** [comment]
bonjour,

Merci pour l'intérêt porté à ma solution.

Domonode est né de ma volonté d'avoir une solution de gestion de ma domotique qui adressait ce que je considérais comme des "limites d'architecture" de Jeedom:


Pour moi, Jeedom a une stack technique (à mon sens) déphasée avec le besoin initial. Un serveur domotique c'est pour moi un démon qui doit communiquer avec d'autres entités, réagir à des événements et en initier lui même (scénarios, ...). Et accessoirement, proposer une GUI pour les interactions avec l'utilisateur, entre autre.

Or jeedom a d'abord été pensé en tant que GUI avec une stack techno type LAMP. Une stack dont le concept de base est de répondre à une requête faite par un tiers (typiquement un utilisateur depuis son browser). D'où les contorsions inextricables pour faire rentrer les autres besoins au chausse pied dans cette stack pas faite pour. Genre:

- Le plugin zwave, c'est un démon python qui va appeler des pages php à chaque fois qu'un événement se produit, et se fera appeler en retour par le php pour initier des actions.

- Un scénario qui doit se déclencher à intervalles réguliers, c'est une tâche cron qui va appeler une page php pour initier une action. etc...

NextDom étant un fork de jeedom, son 'core' se base sur le même paradigme que son papa. Comme cette orientation n'est pas vraiment en ligne avec ma 'vision' (avec des grands guillemets) de l'architecture d'un soft de gestion de domotique, il me semble donc difficile dans ce contexte de mutualiser les besoins et philosophies.
